import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedTravellabWidget2.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedListRadioOffWidget.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedListRadioOnWidget.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedWeresettingupWidget1.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedListRadioOffWidget1.dart';
import 'package:flutterapp/travellabapp/generatedmoneywidget/generated/GeneratedGroup66Widget3.dart';

/* Frame money
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMoneyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 63, 71, 86),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 224.0,
                height: 84.0,
                child: GeneratedWeresettingupWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 18.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 233.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 58.0,
                child: GeneratedGroup66Widget3(),
              ),
              Positioned(
                left: 278.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedNextWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 48.0,
                child: GeneratedListRadioOnWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 48.0,
                child: GeneratedListRadioOffWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 48.0,
                child: GeneratedListRadioOffWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 36.0,
                child: GeneratedTravellabWidget2(),
              )
            ]),
      ),
    ));
  }
}
