import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedAmsterdamNetherlandsWidget1.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedExplorecultureWidget.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedVideosaboutNetherlandsWidget.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedGroup62Widget1.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedGroup65Widget1.dart';
import 'package:flutterapp/travellabapp/generatedculturewidget/generated/GeneratedSeemoreWidget1.dart';

/* Frame culture
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCultureWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 245, 245, 248),
                      ),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 132.0,
                      right: null,
                      bottom: null,
                      width: 276.0,
                      height: 43.0,
                      child: GeneratedExplorecultureWidget(),
                    ),
                    Positioned(
                      left: 54.59857177734375,
                      top: 74.0,
                      right: null,
                      bottom: null,
                      width: 22.0,
                      height: 14.666666030883789,
                      child: GeneratedVectorWidget12(),
                    ),
                    Positioned(
                      left: 294.0,
                      top: 628.0,
                      right: null,
                      bottom: null,
                      width: 72.0,
                      height: 20.0,
                      child: GeneratedSeemoreWidget1(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 222.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 60.0,
                      child: GeneratedGroup65Widget1(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 227.0,
                      height: 23.0,
                      child: GeneratedVideosaboutNetherlandsWidget(),
                    ),
                    Positioned(
                      left: 259.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 38.0,
                      child: GeneratedAmsterdamNetherlandsWidget1(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 389.0,
                      right: null,
                      bottom: null,
                      width: 706.0,
                      height: 208.0,
                      child: GeneratedFrame8Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 796.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 100.0,
              child: GeneratedGroup62Widget1(),
            )
          ]),
    ));
  }
}
