import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedMyprofileWidget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedGroup62Widget5.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedChangeWidget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedGroup58Widget.dart';
import 'package:flutterapp/travellabapp/generatedprofilewidget/generated/GeneratedGroup59Widget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 245, 245, 248),
                      ),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 132.0,
                      right: null,
                      bottom: null,
                      width: 183.0,
                      height: 43.0,
                      child: GeneratedMyprofileWidget(),
                    ),
                    Positioned(
                      left: 307.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 62.0,
                      height: 23.0,
                      child: GeneratedChangeWidget(),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 216.0,
                      right: null,
                      bottom: null,
                      width: 311.0,
                      height: 197.0,
                      child: GeneratedFrame1Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 435.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 60.0,
                      child: GeneratedGroup57Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 515.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 60.0,
                      child: GeneratedGroup58Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 595.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 60.0,
                      child: GeneratedGroup59Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 675.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 60.0,
                      child: GeneratedGroup60Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 52.0,
              top: 818.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 31.0,
              child: GeneratedGroup62Widget5(),
            )
          ]),
    ));
  }
}
