import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedSeemoreWidget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedExploreplacesWidget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedAmsterdamNetherlandsWidget.dart';
import 'package:flutterapp/travellabapp/generatedplaceswidget/generated/GeneratedWefoundawesomeplacessuitabletoyourfinancialstatusWidget.dart';

/* Frame places
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlacesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 245, 245, 248),
                      ),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 132.0,
                      right: null,
                      bottom: null,
                      width: 261.0,
                      height: 43.0,
                      child: GeneratedExploreplacesWidget(),
                    ),
                    Positioned(
                      left: 54.59857177734375,
                      top: 74.0,
                      right: null,
                      bottom: null,
                      width: 22.0,
                      height: 14.666666030883789,
                      child: GeneratedVectorWidget1(),
                    ),
                    Positioned(
                      left: 311.0,
                      top: 465.0,
                      right: null,
                      bottom: null,
                      width: 72.0,
                      height: 20.0,
                      child: GeneratedSeemoreWidget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 222.0,
                      right: null,
                      bottom: null,
                      width: 314.0,
                      height: 60.0,
                      child: GeneratedGroup65Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 373.0,
                      right: null,
                      bottom: null,
                      width: 87.0,
                      height: 3.0,
                      child: GeneratedRectangle1Widget(),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 343.0,
                      right: null,
                      bottom: null,
                      width: 395.0,
                      height: 21.0,
                      child: GeneratedGroup70Widget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 416.0,
                      right: null,
                      bottom: null,
                      width: 325.0,
                      height: 38.0,
                      child:
                          GeneratedWefoundawesomeplacessuitabletoyourfinancialstatusWidget(),
                    ),
                    Positioned(
                      left: 259.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 107.0,
                      height: 38.0,
                      child: GeneratedAmsterdamNetherlandsWidget(),
                    ),
                    Positioned(
                      left: 50.0,
                      top: 521.0,
                      right: null,
                      bottom: null,
                      width: 564.0,
                      height: 186.0,
                      child: GeneratedFrame7Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 52.0,
              top: 818.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 31.0,
              child: GeneratedGroup62Widget(),
            )
          ]),
    ));
  }
}
