import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedWemakethetransitiontoanothercultureeasierWidget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedToyFaces_Tansparent_BG_321Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedToyFaces_Tansparent_BG_29Widget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedTravellabWidget.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/travellabapp/generatedmainwidget/generated/GeneratedVectorWidget.dart';

/* Frame main
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 58, 160, 255),
                ),
              ),
              Positioned(
                left: 49.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 73.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 241.4773406982422,
                top: 471.0,
                right: null,
                bottom: null,
                width: 225.39828491210938,
                height: 298.540771484375,
                child: GeneratedToyFaces_Tansparent_BG_29Widget(),
              ),
              Positioned(
                left: 175.92276000976562,
                top: 679.9712524414062,
                right: null,
                bottom: null,
                width: 272.4671325683594,
                height: 160.3417205810547,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: -33.0,
                top: 472.1082458496094,
                right: null,
                bottom: null,
                width: 346.0,
                height: 344.99993896484375,
                child: GeneratedToyFaces_Tansparent_BG_321Widget(),
              ),
              Positioned(
                left: -63.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 408.0,
                height: 175.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 64.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedGroup66Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 61.0,
                child: GeneratedTravellabWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10869565217391304;
                  double scaleX = (constraints.maxWidth * percentWidth) / 45.0;

                  double percentHeight = 0.05022321428571429;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 45.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.15217391304347827,
                        translateY: constraints.maxHeight * 0.078125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 49.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 62.0,
                child:
                    GeneratedWemakethetransitiontoanothercultureeasierWidget(),
              )
            ]),
      ),
    ));
  }
}
