import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedWeresettingupWidget.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedGroup66Widget2.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedNextWidget.dart';
import 'package:flutterapp/travellabapp/generatedcountrywidget/generated/GeneratedTravellabWidget1.dart';

/* Frame country
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCountryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 63, 71, 86),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 224.0,
                height: 84.0,
                child: GeneratedWeresettingupWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 59.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 59.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 233.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 58.0,
                child: GeneratedGroup66Widget2(),
              ),
              Positioned(
                left: 278.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 26.0,
                child: GeneratedNextWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 36.0,
                child: GeneratedTravellabWidget1(),
              )
            ]),
      ),
    ));
  }
}
