import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedVectorWidget41.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedSignoutWidget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedIcoutlinestickynote2Widget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedMdimapmarkerradiusWidget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedExploreplacesWidget1.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedExplorecultureWidget1.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedExplorerefugeecouncilsWidget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/travellabapp/generatedmenuwidget/generated/GeneratedMdialienoutlineWidget.dart';

/* Frame menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 63, 71, 86),
                ),
              ),
              Positioned(
                left: 91.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 28.0,
                child: GeneratedExploreplacesWidget1(),
              ),
              Positioned(
                left: 94.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 28.0,
                child: GeneratedExplorecultureWidget1(),
              ),
              Positioned(
                left: 91.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 28.0,
                child: GeneratedExplorerefugeecouncilsWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 31.0,
                child: GeneratedSignoutWidget(),
              ),
              Positioned(
                left: 129.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 0.000010490733075130265,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 0.30000001192092896,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcoutlinestickynote2Widget(),
              ),
              Positioned(
                left: 54.59857177734375,
                top: 74.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 14.666666030883789,
                child: GeneratedVectorWidget41(),
              ),
              Positioned(
                left: 55.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdimapmarkerradiusWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedMdialienoutlineWidget(),
              )
            ]),
      ),
    ));
  }
}
