import 'package:flutter/material.dart';
import 'package:flutterapp/travellabapp/generatedregisterwidget1/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/travellabapp/generatedregisterwidget1/generated/GeneratedGroup62Widget4.dart';
import 'package:flutterapp/travellabapp/generatedregisterwidget1/generated/GeneratedSignInWidget2.dart';
import 'package:flutterapp/travellabapp/generatedregisterwidget1/generated/GeneratedTravellabWidget4.dart';
import 'package:flutterapp/travellabapp/generatedregisterwidget1/generated/GeneratedRegisterWidget2.dart';

/* Frame register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 248),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 46.0,
                child: GeneratedRegisterWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 775.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 70.0,
                child: GeneratedGroup62Widget4(),
              ),
              Positioned(
                left: 177.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 23.0,
                child: GeneratedSignInWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 415.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 36.0,
                child: GeneratedTravellabWidget4(),
              )
            ]),
      ),
    ));
  }
}
